INSERT INTO administrators (name, contact_information) VALUES
('Adcap Asset Management S.G.F.C.I.S.A.', NULL),
('Administradora de Titulos Valores S.G.F.C.I.S.A.', NULL),
('Allaria Fondos Administrados S.G.F.C.I.S.A.', NULL),
('Argenfunds S.A.', NULL),
('Axis S.G.F.C.I.S.A.', NULL),
('BACS Administradora de Activos S.A.S.G.F.C.I', NULL),
('Balanz S.G.F.C.I.S.A.U.', NULL),
('Bancor Fondos S.G.F.C.I.S.A.U.', NULL),
('BAVSA Fondos S.A.', NULL),
('BBVA Asset Management Argentina S.A.U.S.G.F.C.I.', NULL),
('BNP Paribas Asset Management  Arg. S.A.S.G.F.C.I', NULL),
('Bull Market Asset Management S.A.', NULL),
('C y C Administradora de Fondos S.A.', NULL),
('Capital Markets Argentina Asset Management S.A.', NULL),
('Cima S.G.F.C.I.S.A.', NULL),
('CMF Asset Management S.A.U.', NULL),
('Cocos Asset Management S.A.', NULL),
('Cohen S.A.', NULL),
('Consultatio Asset Management G.F.C.I.S.A.', NULL),
('Delta Asset Management S.A.', NULL),
('Dracma S.A.', NULL),
('First Capital Markets S.A.', NULL),
('Galicia Asset Management S.A.U.', NULL),
('Galileo Argentina S.G.F.C.I.S.A.', NULL),
('GMC Asset Management S.A.U.', NULL),
('Grupo SS S.A.S.G.F.C.I.', NULL),
('HSBC Global Asset Management Argentina S.A.S.G.F.C.I.', NULL),
('ICBC Investments Argentina S.A.U.S.G.F.C.I.', NULL),
('IEB S.A.', NULL),
('Industrial Asset Management S.G.F.C.I.S.A.', NULL),
('Investis Asset Management S.A.S.G.F.C.I.', NULL),
('Itau Asset Management S.A.S.G.F.C.I.', NULL),
('Macro Fondos S.G.F.C.I.S.A.', NULL),
('Mariva Asset Management S.A.U.S.G.F.C.I.', NULL),
('Max Capital Asset Management S.A.', NULL),
('MEGA QM S.A.', NULL),
('Mercofond S.G.F.C.I.S.A.', NULL),
('Nativa S.G.F.C.I.S.A.', NULL),
('Novus Asset Management S.A.', NULL),
('Nuevo Chaco Fondos S.A.S.G.F.C.I.', NULL),
('Patagonia Inversora S.A.S.G.F.C.I', NULL),
('Pellegrini S.A.S.G.F.C.I.', NULL),
('Proahorro Administradora de Activos S.A.', NULL),
('Provinfondos S.A.S.G.F.C.I.', NULL),
('Quiron Asset Management S.A.', NULL),
('Santander Rio Asset Management G.F.C.I.S.A.', NULL),
('SBS Asset Management S.A.S.G.F.C.I.', NULL),
('Schroder S.A.S.G.F.C.I.', NULL),
('Southern Trust S.G.F.C.I.S.A.', NULL),
('StoneX Asset Management S.A.', NULL),
('Supervielle Asset Management S.A.', NULL),
('Tavelli y Cia. S.A.', NULL),
('Tutelar Inversora S.A.', NULL),
('Ualintec Inversiones S.A.U.S.G.F.C.I.', NULL),
('Valiant Asset Management S.G.F.C.I.S.A.U.', NULL),
('Zofingen Investment S.A.', NULL);
