INSERT INTO administrators (name, contact_information) VALUES
('Santander Rio Asset Management G.F.C.I.S.A.', NULL),
('Pellegrini S.A.S.G.F.C.I.', NULL),
('BBVA Asset Management Argentina S.A.U.S.G.F.C.I.', NULL),
('Industrial Asset Management S.G.F.C.I.S.A.', NULL),
('HSBC Global Asset Management Argentina S.A.S.G.F.C.I.', NULL),
('Macro Fondos S.G.F.C.I.S.A.', NULL),
('Balanz S.G.F.C.I.S.A.U.', NULL),
('ICBC Investments Argentina S.A.U.S.G.F.C.I.', NULL),
('Schroder S.A.S.G.F.C.I.', NULL),
('Delta Asset Management S.A.', NULL),
('MEGA QM S.A.', NULL),
('Patagonia Inversora S.A.S.G.F.C.I', NULL),
('Allaria Fondos Administrados S.G.F.C.I.S.A.', NULL),
('Galicia Asset Management S.A.U.', NULL),
('Adcap Asset Management S.G.F.C.I.S.A.', NULL),
('SBS Asset Management S.A.S.G.F.C.I.', NULL),
('StoneX Asset Management S.A.', NULL),
('Provinfondos S.A.S.G.F.C.I.', NULL),
('Investis Asset Management S.A.S.G.F.C.I.', NULL);
