INSERT INTO depositories (name, contact_information) VALUES
('Banco C.M.F. S.A.', NULL),
('Banco Comafi S.A.', NULL),
('Banco Credicoop Coop. Ltdo.', NULL),
('Banco Credito y Securitizacion S.A.', NULL),
('Banco de Cordoba S.A.', NULL),
('Banco de Galicia y Buenos Aires S.A.', NULL),
('Banco de La Nacion Argentina', NULL),
('Banco de Servicios y Transacciones S.A.', NULL),
('Banco de Valores S.A.', NULL),
('Banco Industrial S.A.', NULL),
('Banco Itau Argentina S.A.', NULL),
('Banco Macro S.A.', NULL),
('Banco Mariva S.A.', NULL),
('Banco Patagonia S.A.', NULL),
('Banco Provincia de Buenos Aires', NULL),
('Banco Santander Argentina S.A.', NULL),
('Banco Supervielle S.A.', NULL),
('BBVA Argentina S.A.', NULL),
('BNP Paribas', NULL),
('Deutsche Bank S.A.', NULL),
('HSBC Bank Argentina S.A.', NULL),
('ICBC (Arg) S.A.', NULL),
('Nuevo Banco del Chaco S.A.', NULL);
